version: '3.7' #version of docker-compose 

services:

  www:
    container_name: www
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app' #persisting data -- ask brock
    ports:
      - 80:3000
    command: ["bash", "-c", "npm start"]

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8080:5000
    command: ["bash", "-c", "nodemon server.js"]
    